[database]
;driver = mysql
host = localhost
;port = 3306
schema =
db_name = app_db 
user_name = root
password = root
sql_sock = /Applications/MAMP/tmp/mysql/mysql.sock
[app]
base_url = http://localhost:8888/frameWorkLightPHP

[POST]
path = /rest/serveurRest.php

[AUTH]
path = /rest/authRest.php




