[database]
;driver = mysql
host = localhost
;port = 3306
schema =
db_name = app_db 
user_name = root
password = root
sql_sock = /Applications/MAMP/tmp/mysql/mysql.sock
[POST]
url = http://localhost:8888/frameWorkLightPHP/rest/serveurRest.php

[AUTH]
url = http://localhost:8888/frameWorkLightPHP/rest/authRest.php




